server.port=8084
spring.application.name=group-session-service

spring.datasource.url=jdbc:postgresql://localhost:5432/groupsessiondb
spring.datasource.username=jacobo
spring.datasource.password=jacobo123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health,info

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=TuPasswordSegura123!

# Exchange y routing keys
rabbitmq.exchange=mindbridge.exchange
rabbitmq.routing-key.session-requested=session.requested
rabbitmq.routing-key.session-approved=session.approved
rabbitmq.routing-key.session-enrolled=session.enrolled
rabbitmq.routing-key.session-cancelled=session.cancelled